//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrePost_ESAN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SisEdutivaEntities6 : DbContext
    {
        public SisEdutivaEntities6()
            : base("name=SisEdutivaEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLPAGOSDT> TBLPAGOSDT { get; set; }
    
        public virtual ObjectResult<SP_Gestionar_Pagos_Result> SP_Gestionar_Pagos(Nullable<int> iDCliente, string cliente, Nullable<int> dNI, Nullable<decimal> precio, Nullable<int> opc, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<bool> checkBox, string eleccion, string nombreArchivo)
        {
            var iDClienteParameter = iDCliente.HasValue ?
                new ObjectParameter("IDCliente", iDCliente) :
                new ObjectParameter("IDCliente", typeof(int));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var dNIParameter = dNI.HasValue ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var checkBoxParameter = checkBox.HasValue ?
                new ObjectParameter("CheckBox", checkBox) :
                new ObjectParameter("CheckBox", typeof(bool));
    
            var eleccionParameter = eleccion != null ?
                new ObjectParameter("Eleccion", eleccion) :
                new ObjectParameter("Eleccion", typeof(string));
    
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("NombreArchivo", nombreArchivo) :
                new ObjectParameter("NombreArchivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Gestionar_Pagos_Result>("SP_Gestionar_Pagos", iDClienteParameter, clienteParameter, dNIParameter, precioParameter, opcParameter, fechaInicioParameter, fechaFinParameter, checkBoxParameter, eleccionParameter, nombreArchivoParameter);
        }
    }
}
