//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrePost_ESAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPAGOSDT
    {
        public int IDCliente { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> DNI { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> CheckBox { get; set; }
        public string Eleccion { get; set; }
        public string NombreArchivo { get; set; }
    }
}
